import type {
  Category,
  Material,
  Occasion,
  Season,
  WardrobeColor,
  WardrobeStyle,
} from "@/lib/wardrobe/constants";

export type DemoWardrobeItem = {
  demoKey: string;
  name: string;
  category: Category;
  primaryColor: WardrobeColor;
  material: Material;
  style: WardrobeStyle;
  seasons: Season[];
  occasions: Occasion[];
};

export const DEMO_WARDROBE: DemoWardrobeItem[] = [
  {
    demoKey: "cloud-white-tee",
    name: "云白棉质 T 恤",
    category: "tops",
    primaryColor: "white",
    material: "cotton",
    style: "minimal",
    seasons: ["spring", "summer", "autumn"],
    occasions: ["casual"],
  },
  {
    demoKey: "mist-blue-linen-shirt",
    name: "雾蓝亚麻衬衫",
    category: "tops",
    primaryColor: "blue",
    material: "linen",
    style: "commute",
    seasons: ["spring", "summer"],
    occasions: ["commute", "casual"],
  },
  {
    demoKey: "midnight-knit-top",
    name: "深夜针织上衣",
    category: "tops",
    primaryColor: "black",
    material: "knit",
    style: "minimal",
    seasons: ["autumn", "winter"],
    occasions: ["commute", "date"],
  },
  {
    demoKey: "coral-sport-tank",
    name: "珊瑚运动背心",
    category: "tops",
    primaryColor: "red",
    material: "synthetic",
    style: "sporty",
    seasons: ["summer"],
    occasions: ["sport", "casual"],
  },
  {
    demoKey: "indigo-straight-jeans",
    name: "靛蓝直筒牛仔裤",
    category: "bottoms",
    primaryColor: "navy",
    material: "denim",
    style: "casual",
    seasons: ["spring", "autumn", "winter"],
    occasions: ["casual", "commute"],
  },
  {
    demoKey: "sand-wide-trousers",
    name: "沙色阔腿裤",
    category: "bottoms",
    primaryColor: "beige",
    material: "linen",
    style: "elegant",
    seasons: ["spring", "summer", "autumn"],
    occasions: ["commute", "date"],
  },
  {
    demoKey: "charcoal-work-pants",
    name: "炭灰通勤西裤",
    category: "bottoms",
    primaryColor: "gray",
    material: "wool",
    style: "commute",
    seasons: ["spring", "autumn", "winter"],
    occasions: ["commute", "formal"],
  },
  {
    demoKey: "forest-sport-shorts",
    name: "墨绿运动短裤",
    category: "bottoms",
    primaryColor: "green",
    material: "synthetic",
    style: "sporty",
    seasons: ["summer"],
    occasions: ["sport", "casual"],
  },
  {
    demoKey: "black-evening-dress",
    name: "黑色小礼裙",
    category: "dresses",
    primaryColor: "black",
    material: "silk",
    style: "elegant",
    seasons: ["spring", "summer", "autumn"],
    occasions: ["date", "formal"],
  },
  {
    demoKey: "lavender-knit-dress",
    name: "薰衣草针织连衣裙",
    category: "dresses",
    primaryColor: "purple",
    material: "knit",
    style: "vintage",
    seasons: ["spring", "autumn", "winter"],
    occasions: ["date", "casual"],
  },
  {
    demoKey: "navy-shirt-dress",
    name: "海军蓝衬衫裙",
    category: "dresses",
    primaryColor: "navy",
    material: "cotton",
    style: "commute",
    seasons: ["spring", "summer", "autumn"],
    occasions: ["commute", "casual"],
  },
  {
    demoKey: "blush-date-dress",
    name: "樱粉约会裙",
    category: "dresses",
    primaryColor: "pink",
    material: "silk",
    style: "elegant",
    seasons: ["spring", "summer"],
    occasions: ["date"],
  },
  {
    demoKey: "oat-knit-cardigan",
    name: "燕麦针织开衫",
    category: "outerwear",
    primaryColor: "beige",
    material: "knit",
    style: "casual",
    seasons: ["spring", "autumn"],
    occasions: ["casual", "commute"],
  },
  {
    demoKey: "caramel-short-jacket",
    name: "焦糖短夹克",
    category: "outerwear",
    primaryColor: "brown",
    material: "leather",
    style: "vintage",
    seasons: ["spring", "autumn"],
    occasions: ["casual", "date"],
  },
  {
    demoKey: "fog-wool-coat",
    name: "雾灰羊毛大衣",
    category: "outerwear",
    primaryColor: "gray",
    material: "wool",
    style: "minimal",
    seasons: ["autumn", "winter"],
    occasions: ["commute", "formal"],
  },
  {
    demoKey: "navy-trench-coat",
    name: "海军蓝风衣",
    category: "outerwear",
    primaryColor: "navy",
    material: "synthetic",
    style: "commute",
    seasons: ["spring", "autumn"],
    occasions: ["commute", "formal"],
  },
  {
    demoKey: "clean-white-sneakers",
    name: "净白休闲鞋",
    category: "shoes",
    primaryColor: "white",
    material: "leather",
    style: "casual",
    seasons: ["spring", "summer", "autumn"],
    occasions: ["casual", "commute"],
  },
  {
    demoKey: "black-loafers",
    name: "黑色乐福鞋",
    category: "shoes",
    primaryColor: "black",
    material: "leather",
    style: "commute",
    seasons: ["spring", "autumn", "winter"],
    occasions: ["commute", "formal"],
  },
  {
    demoKey: "chestnut-boots",
    name: "栗棕短靴",
    category: "shoes",
    primaryColor: "brown",
    material: "leather",
    style: "vintage",
    seasons: ["autumn", "winter"],
    occasions: ["casual", "date"],
  },
  {
    demoKey: "violet-running-shoes",
    name: "雾紫跑鞋",
    category: "shoes",
    primaryColor: "purple",
    material: "synthetic",
    style: "sporty",
    seasons: ["spring", "summer", "autumn", "winter"],
    occasions: ["sport"],
  },
  {
    demoKey: "black-work-tote",
    name: "黑色通勤托特包",
    category: "accessories",
    primaryColor: "black",
    material: "leather",
    style: "commute",
    seasons: ["spring", "summer", "autumn", "winter"],
    occasions: ["commute", "formal"],
  },
  {
    demoKey: "beige-baseball-cap",
    name: "米色棒球帽",
    category: "accessories",
    primaryColor: "beige",
    material: "cotton",
    style: "casual",
    seasons: ["spring", "summer", "autumn"],
    occasions: ["casual", "sport"],
  },
  {
    demoKey: "coral-silk-scarf",
    name: "珊瑚丝巾",
    category: "accessories",
    primaryColor: "red",
    material: "silk",
    style: "elegant",
    seasons: ["spring", "autumn"],
    occasions: ["commute", "date", "formal"],
  },
  {
    demoKey: "silver-sport-bag",
    name: "银灰运动腰包",
    category: "accessories",
    primaryColor: "gray",
    material: "synthetic",
    style: "sporty",
    seasons: ["spring", "summer", "autumn", "winter"],
    occasions: ["sport", "casual"],
  },
];

const DEMO_WARDROBE_KEYS = new Set(DEMO_WARDROBE.map((item) => item.demoKey));

export function getDemoWardrobeImageUrl(demoKey: string | null) {
  if (!demoKey || !DEMO_WARDROBE_KEYS.has(demoKey)) return null;
  return `/demo-wardrobe/${demoKey}.webp`;
}
